### ISSUE TITLE
.biom vs .txt loading w/euk SILVA classifications

### ISSUE THREAD

**Issue by amoliverio** [leffj/mctoolsr#17] opened 2016-03-14 15:26 UTC
loading taxa table + mapping file as input works with .biom output but not .txt output for taxonomy from SILVA

error message with text file (and works fine with same file in biom format):

116 samples loaded
Warning message:
In .parse_taxonomy(data$taxonomy) :
  Issue with provided taxonomy. Check for quotes near line 2. Proceeding without taxonomy.Issue with provided taxonomy. Check for quotes near line 9. [... truncated]

**Comment by leffj** [comment] 2016-03-14 15:30
Thanks for letting me know. Would you mind attaching a reduced mapping file/otu table that is having the problem so I can troubleshoot?

**Comment by amoliverio** [comment] 2016-03-14 15:37
[for mctoolsr.zip](https://github.com/leffj/mctoolsr/files/172249/for.mctoolsr.zip)

**Comment by leffj** [comment] 2016-04-04 21:01
Fixed in v0.0.1.1. Note that the issue was caused by each taxon having many (>15) taxonomy levels, which could be problematic for other reasons, so it's probably better to used the reduced SILVA taxonomy with fewer levels.

**Closed as completed by leffj** 2016-04-04 21:01 UTC
